#!/bin/sh
set -e
service php5.6-fpm start

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

if [ -z "$(ls -A $WORKDIR | grep $PROJECT_NAME)" ]; then
	cd $WORKDIR

	composer create-project --keep-vcs aeria/work $PROJECT_NAME

	if [ ! -z "$(ls -A $WORKDIR/$PROJECT_NAME | grep server)" ]
	then
		ln -sf $WORKDIR/$PROJECT_NAME/server/ $WORKDIR/nginx/$PROJECT_NAME
	fi

	if [ ! -z "$(ls -A $WORKDIR/$PROJECT_NAME | grep nginx)" ]
	then
		ln -sf $WORKDIR/$PROJECT_NAME/nginx/ $WORKDIR/nginx/$PROJECT_NAME
	fi

	env >> "$WORKDIR/$PROJECT_NAME/.env"
fi

exec "$@"