#!/bin/sh
set -e
service php7.0-fpm start

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi


if [ -n "$PROJECT_GIT_HTTPS" -a -z "$(ls -A $WORKDIR)" ]; then
	cd $WORKDIR
	git clone $PROJECT_GIT_HTTPS
	composer install
	mv .env.example .env
fi

exec "$@"