FROM node:latest

# RUN apt-get update -qq \
# 	&& apt-get install -y \
# 	build-essential \
# 	libpq-dev \
# 	libkrb5-dev

RUN mkdir /app

WORKDIR /app

# ADD package.json /app/package.json

# RUN npm install

# ADD . /myapp