#!/bin/sh

if [ ! -z "$(ls -A . | grep package.json)" ]; then
	echo "Package.json found"
	echo $WORKDIR
	echo $PORT

	if [ -z "$(ls -A . | grep yarn.lock)" ]; then
		yarn 	
	fi

	npm run deploy
else
	echo "Package.json not found"
fi


node