#!/bin/sh

if [ ! -z "$(ls -A . | grep package.json)" ]; then
	echo "Package.json found"
	echo $WORKDIR
	echo $PORT

	if [ -z "$(ls -A . | grep yarn.lock)" ]; then
		yarn 	
	else 
		npm install
	fi

	node app.js
else
	echo "Package.json not found"
	node
fi