#!/bin/sh

if [ ! -z "$(ls -A /root | grep init)" ]; then
	mv -r /root/init/* .
	rm -rf /root/init
fi

if [ ! -z "$(ls -A . | grep package.json)" ]; then
	echo "Package.json found"
	echo $WORKDIR
	echo $PORT

	if [ -z "$(ls -A . | grep yarn.lock)" ]; then
		yarn 	
	else 
		npm install
	fi

	node app.js
else
	echo "Package.json not found"
	echo "Launching node so container doesn't die"
	node
fi